"""empty message

Revision ID: bb0263270815
Revises: 9b822c912c45
Create Date: 2020-03-18 10:29:45.218427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0263270815'
down_revision = '9b822c912c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_access', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_access')
    # ### end Alembic commands ###
